import Head from "next/head";
import { useEffect } from "react";
import AssessmentLayout from "@/containers/AssessmentLayout";

export default function Home() {
  // mouse tracker
  useEffect(() => {
    document.documentElement.addEventListener("mouseleave", () =>
      console.log("out")
    );
    document.documentElement.addEventListener("mouseenter", () =>
      console.log("in")
    );

    // audio
    function getLocalStream() {
      navigator.mediaDevices
        .getUserMedia({ video: false, audio: true })
        .then((stream) => {
          window.localStream = stream; // A
          window.localAudio.srcObject = stream; // B
          window.localAudio.autoplay = true; // C
        })
        .catch((err) => {
          console.error(`you got an error: ${err}`);
        });
    }
    getLocalStream();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AssessmentLayout />
    </>
  );
}
